[package]
name = "disarm64-custom"
version = "0.1.1"
edition = "2024"
description = "A custom built version of https://github.com/kromych/disarm64"
license = "MIT"

[dependencies]
bitfield-struct = "0.11.0"
disarm64_defn = { version = "0.1.11", default-features = false }
